spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: stac
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  mail:
    host: localhost
    port: 1025
    username: stac
    password: secret
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6InN0YWMiLCJleHAiOjE3MTM4NjA4OTksImlhdCI6MTcxMzg2MDg5OX0.xEdCUcTK83Soj5iRn47d-svSAnWoLLetLVfw9kiX9_g
      expiration: 8640000